### PR TITLE
allowing stack in UPDATE_ROLLBACK_COMPLETE status to be updated.

### PR DESCRIPTION
**Pull request by skout23**
fix to the gorilla-prod stack not being updated

### CODE REVIEW

**Comment by mkk-fullscreen** [comment]
4d84ef1b68cac9ce9ba393d87a24eadf--goals-nerd

**Comment by skout23** [comment]
```
"standardOutput": "mike.kendall NOT on system, adding"
```

**Comment by mkk-fullscreen** [comment]
@skout23 🍻

**Comment by mkk-fullscreen** [comment]
:beers:

**Pull request merged**
